# Generated by Django 3.1.6 on 2021-02-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
