version: '3.3'

services:
  web:
    build: ./
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-uks_tim_10}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-uks_tim_10}
      - POSTGRES_DB=${POSTGRES_DB:-uks_tim_10_db}

volumes:
  postgres_data:
  static_files: