version: '3.3'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile-local
    command: sh -c "pipenv run python manage.py makemigrations &&
                    pipenv run python manage.py migrate &&
                    pipenv run python manage.py createsuperuser --username admin --noinput --email 'admin@admin.com' &&
                    pipenv run gunicorn uks.wsgi:application --bind 0.0.0.0:${PORT}"
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-uks_tim_10}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-uks_tim_10}
      - POSTGRES_DB=${POSTGRES_DB:-uks_tim_10_db}

volumes:
  postgres_data:
  static_files: