# Generated by Django 3.1.5 on 2021-02-14 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('version_control', '0002_auto_20210215_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPENED', 'OPENED'), ('CLOSED', 'CLOSED')], max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version_control.organization')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version_control.repository')),
            ],
        ),
    ]
