# Generated by Django 3.1.5 on 2021-02-16 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version_control', '0002_auto_20210215_0004'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='version_control.organization'),
        ),
        migrations.AlterField(
            model_name='project',
            name='repository',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='version_control.repository'),
        ),
    ]
