# Generated by Django 3.1.5 on 2021-02-16 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version_control', '0002_auto_20210215_0004'),
        ('projects', '0002_auto_20210216_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version_control.organization'),
        ),
        migrations.AlterField(
            model_name='project',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version_control.repository'),
        ),
    ]
