# Generated by Django 3.1.5 on 2021-02-08 19:41

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version_control.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('dueDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('isClosed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('members', models.ManyToManyField(to='version_control.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version_control.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('isPrivate', models.BooleanField()),
                ('contributors', models.ManyToManyField(to='version_control.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('createdOn', models.DateTimeField(default=django.utils.timezone.now)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version_control.repository')),
            ],
        ),
        migrations.CreateModel(
            name='WikiRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatedOn', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version_control.appuser')),
                ('wiki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version_control.wiki')),
            ],
        ),
        migrations.CreateModel(
            name='TaskRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatedOn', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('TO_DO', 'IN'), ('IN_PROGRESS', 'IN_PROGRESS'), ('IN_REVIEW', 'IN_REVIEW'), ('DONE', 'DONE'), ('ARCHIVED', 'ARCHIVED')], max_length=255)),
                ('reviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version_control.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('assignees', models.ManyToManyField(to='version_control.AppUser')),
                ('labels', models.ManyToManyField(to='version_control.Label')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version_control.milestone')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version_control.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version_control.repository'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version_control.repository'),
        ),
        migrations.AddField(
            model_name='label',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version_control.repository'),
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('commitedOn', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version_control.branch')),
                ('commitedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version_control.appuser')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version_control.repository'),
        ),
    ]
