# Generated by Django 3.1.6 on 2021-02-19 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version_control', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commit',
        ),
    ]
