# Generated by Django 3.1.5 on 2021-02-17 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version_control', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskrevision',
            name='reviser',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskRevision',
        ),
    ]
