# Generated by Django 3.1.6 on 2021-02-15 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version_control', '0002_auto_20210214_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikirevision',
            name='reviser',
        ),
        migrations.RemoveField(
            model_name='wikirevision',
            name='wiki',
        ),
        migrations.DeleteModel(
            name='Wiki',
        ),
        migrations.DeleteModel(
            name='WikiRevision',
        ),
    ]
