# Generated by Django 3.1.5 on 2021-02-15 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_auto_20210215_0020'),
        ('repository', '0001_initial'),
        ('version_control', '0002_auto_20210214_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.repository'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.repository'),
        ),
        migrations.AlterField(
            model_name='project',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.repository'),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.repository'),
        ),
        migrations.DeleteModel(
            name='Repository',
        ),
    ]
