# Generated by Django 3.1.5 on 2021-02-19 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version_control', '0002_delete_commit'),
        ('version_control', '0003_auto_20210219_2313'),
    ]

    operations = [
    ]
