# Generated by Django 3.1.6 on 2021-02-16 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0001_initial'),
        ('version_control', '0003_auto_20210215_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='milestone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milestones.milestone'),
        ),
        migrations.DeleteModel(
            name='Milestone',
        ),
    ]
