# Generated by Django 3.1.6 on 2021-02-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_auto_20210217_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
