# Generated by Django 3.1.5 on 2021-02-19 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='contributors',
            field=models.ManyToManyField(related_name='contributors', to='users.Profile'),
        ),
    ]
